-- Administracion segura de registros enviados por Canelillo Harvest.
-- Ejecutar una vez en Supabase SQL Editor con un usuario propietario del esquema public.

begin;

create table if not exists public.registros_trazabilidad_auditoria (
  id bigint generated by default as identity primary key,
  registro_id bigint not null,
  operacion text not null check (operacion in ('UPDATE', 'DELETE')),
  datos_anteriores jsonb not null,
  datos_nuevos jsonb,
  usuario_id uuid,
  usuario_nombre text,
  creado_en timestamptz not null default now()
);

create index if not exists registros_trazabilidad_auditoria_registro_idx
  on public.registros_trazabilidad_auditoria (registro_id, creado_en desc);

create index if not exists registros_trazabilidad_auditoria_fecha_idx
  on public.registros_trazabilidad_auditoria (creado_en desc);

create or replace function public.auditar_registro_trazabilidad()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_usuario_id uuid := auth.uid();
  v_usuario_nombre text;
begin
  select u.nombre_completo
    into v_usuario_nombre
  from public.usuarios u
  where u.id = v_usuario_id;

  insert into public.registros_trazabilidad_auditoria (
    registro_id,
    operacion,
    datos_anteriores,
    datos_nuevos,
    usuario_id,
    usuario_nombre
  ) values (
    old.id,
    tg_op,
    to_jsonb(old),
    case when tg_op = 'UPDATE' then to_jsonb(new) else null end,
    v_usuario_id,
    coalesce(v_usuario_nombre, auth.jwt() ->> 'email', 'Sistema')
  );

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists registros_trazabilidad_auditoria_trg on public.registros_trazabilidad;
create trigger registros_trazabilidad_auditoria_trg
before update or delete on public.registros_trazabilidad
for each row execute function public.auditar_registro_trazabilidad();

alter table public.registros_trazabilidad enable row level security;
alter table public.registros_trazabilidad_auditoria enable row level security;

drop policy if exists "harvest_admin_update" on public.registros_trazabilidad;
drop policy if exists "harvest_admin_update_guard" on public.registros_trazabilidad;
drop policy if exists "harvest_admin_delete" on public.registros_trazabilidad;
drop policy if exists "harvest_admin_delete_guard" on public.registros_trazabilidad;

create policy "harvest_admin_update"
on public.registros_trazabilidad
for update
to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.activo is true
      and lower(u.rol::text) in ('admin', 'administrador')
  )
)
with check (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.activo is true
      and lower(u.rol::text) in ('admin', 'administrador')
  )
);

create policy "harvest_admin_delete"
on public.registros_trazabilidad
for delete
to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.activo is true
      and lower(u.rol::text) in ('admin', 'administrador')
  )
);

drop policy if exists "harvest_admin_read_audit" on public.registros_trazabilidad_auditoria;
create policy "harvest_admin_read_audit"
on public.registros_trazabilidad_auditoria
for select
to authenticated
using (
  exists (
    select 1 from public.usuarios u
    where u.id = auth.uid()
      and u.activo is true
      and lower(u.rol::text) in ('admin', 'administrador')
  )
);

grant update, delete on public.registros_trazabilidad to authenticated;
grant select on public.registros_trazabilidad_auditoria to authenticated;
revoke insert, update, delete on public.registros_trazabilidad_auditoria from anon, authenticated;

commit;
