-- Tabla para guardar la matriz de riego de AgroCore.
-- Ejecutar en Supabase SQL Editor.

begin;

create table if not exists public.riego (
  id bigint generated by default as identity primary key,
  campo_id uuid not null references public.campos(id) on delete cascade,
  fecha date not null,
  horas_riego numeric(8, 2) not null default 0,
  volumen numeric(14, 3) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint riego_campo_fecha_key unique (campo_id, fecha),
  constraint riego_horas_nonnegative check (horas_riego >= 0),
  constraint riego_volumen_nonnegative check (volumen >= 0)
);

create index if not exists riego_fecha_idx
  on public.riego (fecha);

create index if not exists riego_campo_id_idx
  on public.riego (campo_id);

create or replace function public.set_riego_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_riego_updated_at on public.riego;
create trigger trg_riego_updated_at
before update on public.riego
for each row
execute function public.set_riego_updated_at();

alter table public.riego enable row level security;

drop policy if exists riego_select on public.riego;
create policy riego_select
on public.riego
for select
to authenticated
using (true);

drop policy if exists riego_insert on public.riego;
create policy riego_insert
on public.riego
for insert
to authenticated
with check (true);

drop policy if exists riego_update on public.riego;
create policy riego_update
on public.riego
for update
to authenticated
using (true)
with check (true);

drop policy if exists riego_delete on public.riego;
create policy riego_delete
on public.riego
for delete
to authenticated
using (true);

grant select, insert, update, delete on public.riego to authenticated;
grant usage, select on sequence public.riego_id_seq to authenticated;

commit;
