-- Integracion WiseConn -> AgroCore para el campo Canelillo.
-- Ejecutar una vez en Supabase SQL Editor.
-- La API key se configura solamente en el servidor como WISECONN_API_KEY.

begin;

create table if not exists public.wiseconn_campos (
  farm_id bigint primary key,
  nombre_wiseconn text not null,
  nombre_agrocore text not null,
  zona_horaria text not null default 'America/Santiago',
  activo boolean not null default true,
  actualizado_en timestamptz not null default now()
);

create table if not exists public.wiseconn_zona_campos (
  id bigint generated by default as identity primary key,
  farm_id bigint not null references public.wiseconn_campos(farm_id) on delete cascade,
  zone_id bigint not null,
  pump_system_id bigint,
  nombre_zona text not null,
  campo_id uuid references public.campos(id) on delete restrict,
  potrero_agrocore text,
  bloque_agrocore text,
  sincronizar boolean not null default true,
  motivo_exclusion text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint wiseconn_zona_campos_zone_unq unique (farm_id, zone_id),
  constraint wiseconn_zona_campos_destino_ck check (
    (sincronizar and campo_id is not null)
    or (not sincronizar)
  )
);

create unique index if not exists wiseconn_zona_campos_campo_unq
  on public.wiseconn_zona_campos (farm_id, campo_id)
  where sincronizar;

create index if not exists wiseconn_zona_campos_campo_idx
  on public.wiseconn_zona_campos (campo_id);

create table if not exists public.wiseconn_riegos_reales (
  event_id bigint primary key,
  farm_id bigint not null references public.wiseconn_campos(farm_id) on delete cascade,
  zone_id bigint not null,
  inicio timestamptz not null,
  termino timestamptz not null,
  estado text,
  tipo text,
  pump_system_id bigint,
  volumen_m3 numeric(16, 3),
  precipitacion_mm numeric(14, 3),
  caudal_m3_h numeric(14, 3),
  sincronizado_en timestamptz not null default now(),
  constraint wiseconn_riego_periodo_ck check (termino >= inicio)
);

create index if not exists wiseconn_riegos_reales_zone_inicio_idx
  on public.wiseconn_riegos_reales (farm_id, zone_id, inicio);

create index if not exists wiseconn_riegos_reales_inicio_idx
  on public.wiseconn_riegos_reales (inicio);

-- Copia operativa en la tabla principal de riego. Los campos auxiliares
-- permiten conservar el valor WiseConn aunque exista una correccion manual.
alter table public.riego
  add column if not exists potrero text,
  add column if not exists bloque text,
  add column if not exists especie text,
  add column if not exists variedad text,
  add column if not exists hectareas numeric(12, 3),
  add column if not exists precipitacion numeric,
  add column if not exists caudal numeric,
  add column if not exists origen text not null default 'manual',
  add column if not exists wiseconn_volumen_m3 numeric(16, 3),
  add column if not exists wiseconn_horas_calculadas numeric(8, 2),
  add column if not exists wiseconn_eventos integer,
  add column if not exists wiseconn_sincronizado_en timestamptz;

create index if not exists riego_origen_fecha_idx
  on public.riego (origen, fecha);

insert into public.wiseconn_campos (farm_id, nombre_wiseconn, nombre_agrocore, zona_horaria, activo, actualizado_en)
values (4212, 'Canelillo', 'Canelillo', 'America/Santiago', true, now())
on conflict (farm_id) do update set
  nombre_wiseconn = excluded.nombre_wiseconn,
  nombre_agrocore = excluded.nombre_agrocore,
  zona_horaria = excluded.zona_horaria,
  activo = excluded.activo,
  actualizado_en = now();

insert into public.wiseconn_zona_campos (
  farm_id, zone_id, pump_system_id, nombre_zona, campo_id,
  potrero_agrocore, bloque_agrocore, sincronizar, motivo_exclusion, actualizado_en
)
values
  (4212, 217646, 8299, 'P 1 Bloque 1 ', '2fd8cafe-a3aa-4899-87de-97d9d55e18d5'::uuid, '1', '1', true, null, now()),
  (4212, 217647, 8299, 'P1 Bloque 2 ', 'c7f4348d-9623-47b0-baba-253d569342a2'::uuid, '1', '2', true, null, now()),
  (4212, 217648, 8299, 'P1 Bloque 3 ', 'e526ebd5-0c6b-4494-b3c2-f195ffda1089'::uuid, '1', '3', true, null, now()),
  (4212, 217649, 8299, 'P1 Bloque 4 ', 'dd5cbce5-6b95-4968-b608-7c091308abd5'::uuid, '1', '4', true, null, now()),
  (4212, 221614, 8634, 'P19', '34ee8de2-1dae-4513-8c94-0c301e64c152'::uuid, '19', '4', true, null, now()),
  (4212, 217650, 8299, 'P2 B4 Bloque 5', '88e7cfb1-c918-44b6-aafb-664a95a4337d'::uuid, '2', '5', true, null, now()),
  (4212, 217651, 8299, 'P2 B4 Bloque 6 ', 'c1fce3ef-a196-44d0-942a-beb199184411'::uuid, '2', '6', true, null, now()),
  (4212, 217652, 8299, 'P2 B5 Bloque 7 ', 'e0370f29-0f65-4bb3-aea0-28e97c9776af'::uuid, '2', '7', true, null, now()),
  (4212, 217653, 8299, 'P2 B5 Bloque 8', 'fce108fc-2f39-457a-a98b-859f8d7df697'::uuid, '2', '8', true, null, now()),
  (4212, 228359, 9199, 'P 20 B3', '7e2d6809-f5e3-463a-9383-72214bff9c20'::uuid, '20', '3', true, null, now()),
  (4212, 228360, 9199, 'P 20 B4', '79d29558-ab6e-4f85-8f51-8b0edc42b4c1'::uuid, '20', '4', true, null, now()),
  (4212, 228361, 9199, 'P 20 B5', '575b06f8-f4e6-45e4-b70e-32771b2a05a3'::uuid, '20', '5', true, null, now()),
  (4212, 228362, 9199, 'P 20 B6', 'd884f06a-5e5c-4ad6-a645-26779612e770'::uuid, '20', '6', true, null, now()),
  (4212, 228363, 9199, 'P 20A B7', '1eea43bb-c1ca-4e28-a522-c5bac69ebd01'::uuid, '20A', '7', true, null, now()),
  (4212, 228364, 9199, 'P 20A B8', 'e2213472-1553-4b1f-b367-0853fe4721af'::uuid, '20A', '8', true, null, now()),
  (4212, 228366, 9199, 'P 20B B10', 'a3433a2c-2fa1-4295-81fb-4bbddc554553'::uuid, '20B', '10', true, null, now()),
  (4212, 228365, 9199, 'P 20B B9', '2e2d6dcf-e8da-403f-88c6-d764f591484b'::uuid, '20B', '9', true, null, now()),
  (4212, 228369, 9199, 'P 21 B1', '211da4f3-ee2d-42db-9ad8-63fc12d0ab0d'::uuid, '21', '1', true, null, now()),
  (4212, 228370, 9199, 'P 21 B2 ', 'ce685441-cc02-4b2e-8abb-4e4fa0f67c8d'::uuid, '21', '2', true, null, now()),
  (4212, 228982, 9232, 'P22 B1', 'cd2127fc-794e-4091-855c-3afc4cc3df1a'::uuid, '22', '1', true, null, now()),
  (4212, 228983, 9232, 'P22 B2 ', 'ac3f43be-8d0d-4b8c-9d95-6711eeeaea43'::uuid, '22', '2', true, null, now()),
  (4212, 228984, 9232, 'P22 B3', 'd320bb62-cb27-4de4-b674-955e137bc9ca'::uuid, '22', '3', true, null, now()),
  (4212, 228985, 9232, 'P22 B4', 'f1c7f0b5-c17f-4af7-b206-817a33fd164c'::uuid, '22', '4', true, null, now()),
  (4212, 228986, 9232, 'P22 B5', 'fabb841c-1bb0-4044-b6e0-f66f56c1ed68'::uuid, '22', '5', true, null, now()),
  (4212, 228987, 9232, 'P23 B6 ', '50abc32a-4973-4ca5-a41d-830ffbe59563'::uuid, '23', '6', true, null, now()),
  (4212, 228988, 9232, 'P23 B7 ', '057d3542-ade7-40be-9925-e0157d3dc113'::uuid, '23', '7', true, null, now()),
  (4212, 228989, 9232, 'P23 B8', '92e658c6-d197-4bf5-ac0d-c8c30cb4df3f'::uuid, '23', '8', true, null, now()),
  (4212, 228990, 9232, 'P23 B9', '4ebf52eb-a6e2-4be7-8766-b8dc2cd8aa1c'::uuid, '23', '9', true, null, now()),
  (4212, 228367, 9199, 'P 24 B11', 'a36af9c3-1b79-4cae-aaf8-695e2ac3d5de'::uuid, '24', '11', true, null, now()),
  (4212, 228368, 9199, 'P 24 B12', 'bfd12d4c-b1fe-46f1-aab2-7fa466f20b43'::uuid, '24', '12', true, null, now()),
  (4212, 228270, 9189, 'P 25 B1', 'dc299a5a-1fcc-483f-9809-6cdf82c3f603'::uuid, '25', '1', true, null, now()),
  (4212, 228271, 9189, 'P 25 B2 ', '2b35b4f2-df3f-418b-bf81-e9e2c3a60cb1'::uuid, '25', '2', true, null, now()),
  (4212, 228272, 9189, 'P 25 B3 ', '262bfea8-6344-4b17-b600-addc2880e420'::uuid, '25', '3', true, null, now()),
  (4212, 228273, 9189, 'P 25 B4 ', 'a72e4fd4-4a48-4bde-8ef6-f3536823083d'::uuid, '25', '4', true, null, now()),
  (4212, 228274, 9189, 'P 25 B5', '6441f211-fc92-4aa3-8701-a2d7d6454f1e'::uuid, '25', '5', true, null, now()),
  (4212, 228275, 9189, 'P 25 B6', '3b3ca92f-a495-498f-a452-30043078e0ac'::uuid, '25', '6', true, null, now()),
  (4212, 228276, 9189, 'P 25 B7', 'e718a9ba-1bed-45f8-b3b2-2defba7a8bfd'::uuid, '25', '7', true, null, now()),
  (4212, 228277, 9189, 'P 25 B8', '2ddd0a08-5db4-4294-81bc-f19671018293'::uuid, '25', '8', true, null, now()),
  (4212, 56569, 18937, 'Sector 1 Gravedad', '3f9263c3-8e52-4c18-9307-e7c83beefe08'::uuid, '27 GRAV', '1', true, null, now()),
  (4212, 56570, 18937, 'Sector 2 Gravedad', '503cbc36-1390-423e-aa0f-73d3a17f6763'::uuid, '27 GRAV', '2', true, null, now()),
  (4212, 56571, 18937, 'Sector 3 Gravedad', '576a6928-430b-49ba-a482-8141b6e986d2'::uuid, '27 GRAV', '3', true, null, now()),
  (4212, 56572, 18937, 'Sector 4 Gravedad', '23c47b52-b4bd-4ea7-bcd8-538edc8d012d'::uuid, '27 GRAV', '4', true, null, now()),
  (4212, 56574, 18937, 'Sector 5 Gravedad', '680b3f93-506a-4ba5-94ea-4edfb9300630'::uuid, '27 GRAV', '5', true, null, now()),
  (4212, 56561, 18936, 'Sector 1 Impulsión', '23cbf0c5-1603-451b-bb3d-fea94fadb551'::uuid, '27 IMP', '1', true, null, now()),
  (4212, 56562, 18936, 'Sector 2 Impulsión', 'afccb8c4-b3db-4a01-a8bd-acac23ce56ba'::uuid, '27 IMP', '2', true, null, now()),
  (4212, 56563, 18936, 'Sector 3 Impulsión', '7cca6c90-fa0e-4dc5-97d3-8bed092b9f33'::uuid, '27 IMP', '3', true, null, now()),
  (4212, 56564, 18936, 'Sector 4 Impulsión', '3a3ef1f7-a126-4cce-a304-7315a303639e'::uuid, '27 IMP', '4', true, null, now()),
  (4212, 56565, 18936, 'Sector 5 Impulsión', '6f53cd9d-4882-4b71-b45b-6141ddf874cb'::uuid, '27 IMP', '5', true, null, now()),
  (4212, 56566, 18936, 'Sector 6 Impulsión', '76d10cbc-0e36-45f2-869c-0291bfa76f68'::uuid, '27 IMP', '6', true, null, now()),
  (4212, 56567, 18936, 'Sector 7 Impulsión', '6b40d18c-17fe-46b7-8976-bac59a3ce7c5'::uuid, '27 IMP', '7', true, null, now()),
  (4212, 215426, 8064, 'P 28 B1 ', '4db377bb-a701-4c99-a087-fc2fc50076a1'::uuid, '28', '1', true, null, now()),
  (4212, 215427, 8064, 'P 28 B2 ', 'e6593bc4-62e2-421c-a751-0b01ab71dd45'::uuid, '28', '2', true, null, now()),
  (4212, 215428, 8064, 'P 28 B3 ', 'c553db82-1bb2-445b-9a42-fe887f008fb4'::uuid, '28', '3', true, null, now()),
  (4212, 215429, 8064, 'P 28 B4 ', '2d898fb6-ca10-4047-8c9f-fa8c317aa4b4'::uuid, '28', '4', true, null, now()),
  (4212, 215430, 8064, 'P 28 B5', '015d7447-a5b7-4922-9eda-47efb1fc46a9'::uuid, '28', '5', true, null, now()),
  (4212, 215431, 8064, 'P 28 B6', 'ee9ddb96-f97a-4c3a-8cbf-0e5726f1f19c'::uuid, '28', '6', true, null, now()),
  (4212, 215303, 8041, 'P 30 B1', '84130a0d-fa57-4384-8e89-e40f5e4fe1aa'::uuid, '30', '1', true, null, now()),
  (4212, 215304, 8041, 'P 30 B2', '97ccdd72-b649-488f-b53f-77396338f39e'::uuid, '30', '2', true, null, now()),
  (4212, 215305, 8041, 'P 30 B3', '0ea53b1a-6d8c-4675-8308-eab295217cd5'::uuid, '30', '3', true, null, now()),
  (4212, 215306, 8041, 'P 31 B4', '70437f54-9156-4ad6-882c-531674da4cfd'::uuid, '30', '4', true, null, now()),
  (4212, 215307, 8041, 'P 31 B5', 'd9b28577-ed25-4236-948b-0a696933a152'::uuid, '30', '5', true, null, now()),
  (4212, 215308, 8041, 'P 31 B6', '296e8d6a-5ffc-40c9-8abe-14af0996abd2'::uuid, '30', '6', true, null, now()),
  (4212, 215309, 8041, 'P 31 B7', 'e99471f9-3af1-4ea1-9967-bef49df4679b'::uuid, '30', '7', true, null, now()),
  (4212, 221611, 8634, 'P5 B1 ', '45108ae7-088c-4650-add3-4901f14a3f46'::uuid, '5', '1A', true, null, now()),
  (4212, 221612, 8634, 'P5 B2', '73ed20f6-ac07-4eb5-bc5e-4e7c285eb9b8'::uuid, '5', '2', true, null, now()),
  (4212, 221613, 8634, 'P6', 'a541d7d1-5c36-48f4-a4b9-5e0fe811fdde'::uuid, '6', '3', true, null, now()),
  (4212, 216037, 8126, 'P7 B1', '962f22aa-86a2-4c51-95ea-19fc94a2cdfd'::uuid, '7', '1', true, null, now()),
  (4212, 216046, 8126, 'P7 B 10', '459721e4-4202-4a70-a74d-e37d7920303d'::uuid, '7', '10', true, null, now()),
  (4212, 216038, 8126, 'P7 B2 ', '5d619e60-d997-4769-beab-7abb64b08ba8'::uuid, '7', '2', true, null, now()),
  (4212, 216039, 8126, 'P7 B3', '4bcfdef4-6116-405c-a745-06f1ff2efcbe'::uuid, '7', '3', true, null, now()),
  (4212, 216040, 8126, 'P7 B4', '2770b169-8ae1-4def-b9ee-ac477c11eb10'::uuid, '7', '4', true, null, now()),
  (4212, 216041, 8126, 'P7 B5', '77caba84-cc6a-4fa4-8dd1-c8218742ef4c'::uuid, '7', '5', true, null, now()),
  (4212, 216042, 8126, 'P7 B6', 'ca926cb6-4347-4fc0-b41e-fd88160d2810'::uuid, '7', '6', true, null, now()),
  (4212, 216043, 8126, 'P7 B7', 'aa856087-5235-46ab-9ba7-455a3efcda36'::uuid, '7', '7', true, null, now()),
  (4212, 216044, 8126, 'P7 B8', '5a05c01d-15f5-4c77-a999-8a6b2560679e'::uuid, '7', '8', true, null, now()),
  (4212, 216045, 8126, 'P7 B9', '48fbe59b-63f4-431e-90fc-26c667ab2280'::uuid, '7', '9', true, null, now()),
  (4212, 217640, 8298, 'Mirador 1 Sector 1', '8021cd92-6207-481f-ac9b-6d792deaf678'::uuid, 'Mirador 1', '1', true, null, now()),
  (4212, 217641, 8298, 'Mirador 1 Sector 2 ', 'e438f85e-3e18-4d02-a9f0-22ccb5d2705d'::uuid, 'Mirador 1', '2', true, null, now()),
  (4212, 217642, 8298, 'Mirador 1 Sector 3 ', '2d741b2a-9313-43fd-a218-e3da1a67f6c1'::uuid, 'Mirador 1', '3', true, null, now()),
  (4212, 217643, 8298, 'Mirador 1 Sector 4 ', '48c0511f-acc8-4e8c-9db9-d3b0e45ace6c'::uuid, 'Mirador 1', '4', true, null, now()),
  (4212, 217644, 8298, 'Mirador 1 Sector 5 ', '8801b06a-73b5-4595-a778-bb6e83931520'::uuid, 'Mirador 1', '5', true, null, now()),
  (4212, 217645, 8298, 'Mirador 1 Sector 6', '5e39872e-497f-40b9-bd1a-a0e9a05e56e6'::uuid, 'Mirador 1', '6', true, null, now()),
  (4212, 216710, 8209, 'Paltos B1 ', '832f91cb-c27d-4b91-81af-3960d0e70695'::uuid, 'Mirador 2', '1', true, null, now()),
  (4212, 216711, 8209, 'Paltos B2 ', 'c41b664e-78cb-4c63-9213-725333548e42'::uuid, 'Mirador 2', '2', true, null, now()),
  (4212, 216712, 8209, 'Paltos B3 ', '5a6e0300-4bc7-4327-8f2c-efeb7a915504'::uuid, 'Mirador 2', '3', true, null, now()),
  (4212, 216713, 8209, 'Paltos B4 ', '696460ea-904a-4242-ba37-2617734cf44f'::uuid, 'Mirador 2', '4', true, null, now()),
  (4212, 216714, 8209, 'Paltos B5 A', '04145a14-a147-44e4-8963-caa810353811'::uuid, 'Mirador 2', '5A', true, null, now()),
  (4212, 216715, 8209, 'Paltos B5 B', 'c3a82281-5343-4235-9da9-9596223ea7c4'::uuid, 'Mirador 2', '5B', true, null, now()),
  (4212, 217274, 8209, 'Paltos B6 ', '84df33fb-0425-4ff7-b42b-d94f101ef3df'::uuid, 'Mirador 2', '6', true, null, now()),
  (4212, 56568, 18936, 'Sector 8 Impulsion', null, null, null, false, 'Zona tecnica; no corresponde a un sector agricola del campo', now())
on conflict (farm_id, zone_id) do update set
  pump_system_id = excluded.pump_system_id,
  nombre_zona = excluded.nombre_zona,
  campo_id = excluded.campo_id,
  potrero_agrocore = excluded.potrero_agrocore,
  bloque_agrocore = excluded.bloque_agrocore,
  sincronizar = excluded.sincronizar,
  motivo_exclusion = excluded.motivo_exclusion,
  actualizado_en = now();

alter table public.wiseconn_campos enable row level security;
alter table public.wiseconn_zona_campos enable row level security;
alter table public.wiseconn_riegos_reales enable row level security;

drop policy if exists wiseconn_campos_select on public.wiseconn_campos;
create policy wiseconn_campos_select on public.wiseconn_campos
for select to authenticated using (true);

drop policy if exists wiseconn_zona_campos_select on public.wiseconn_zona_campos;
create policy wiseconn_zona_campos_select on public.wiseconn_zona_campos
for select to authenticated using (true);

drop policy if exists wiseconn_riegos_reales_select on public.wiseconn_riegos_reales;
create policy wiseconn_riegos_reales_select on public.wiseconn_riegos_reales
for select to authenticated using (true);

drop policy if exists wiseconn_riegos_reales_insert on public.wiseconn_riegos_reales;
create policy wiseconn_riegos_reales_insert on public.wiseconn_riegos_reales
for insert to authenticated with check (true);

drop policy if exists wiseconn_riegos_reales_update on public.wiseconn_riegos_reales;
create policy wiseconn_riegos_reales_update on public.wiseconn_riegos_reales
for update to authenticated using (true) with check (true);

grant select on public.wiseconn_campos to authenticated;
grant select on public.wiseconn_zona_campos to authenticated;
grant select, insert, update on public.wiseconn_riegos_reales to authenticated;
grant usage, select on sequence public.wiseconn_zona_campos_id_seq to authenticated;

create or replace function public.sincronizar_riego_wiseconn(p_registros jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_procesados integer := 0;
  v_manuales_preservados integer := 0;
begin
  if p_registros is null or jsonb_typeof(p_registros) <> 'array' then
    raise exception 'p_registros debe ser un arreglo JSON';
  end if;

  with entrada as (
    select distinct on (x.campo_id, x.fecha)
      x.campo_id,
      x.fecha,
      round(greatest(coalesce(x.horas, 0), 0)::numeric, 2) as horas,
      round(greatest(coalesce(x.volumen_m3, 0), 0)::numeric, 3) as volumen_m3,
      greatest(coalesce(x.eventos, 0), 0)::integer as eventos,
      c.potrero,
      c.bloque,
      c.especie,
      c.variedad,
      c.hectareas,
      c.precipitacion,
      c.caudal
    from jsonb_to_recordset(p_registros) as x(
      campo_id uuid,
      fecha date,
      horas numeric,
      volumen_m3 numeric,
      eventos integer
    )
    join public.campos c on c.id = x.campo_id
    where x.fecha >= date '2026-01-01'
      and coalesce(x.volumen_m3, 0) > 0
      and coalesce(x.horas, 0) >= 0
    order by x.campo_id, x.fecha
  )
  select count(*)
  into v_manuales_preservados
  from entrada e
  join public.riego r
    on r.campo_id = e.campo_id
   and r.fecha = e.fecha
  where coalesce(nullif(r.origen, ''), 'manual') <> 'wiseconn';

  with entrada as (
    select distinct on (x.campo_id, x.fecha)
      x.campo_id,
      x.fecha,
      round(greatest(coalesce(x.horas, 0), 0)::numeric, 2) as horas,
      round(greatest(coalesce(x.volumen_m3, 0), 0)::numeric, 3) as volumen_m3,
      greatest(coalesce(x.eventos, 0), 0)::integer as eventos,
      c.potrero,
      c.bloque,
      c.especie,
      c.variedad,
      c.hectareas,
      c.precipitacion,
      c.caudal
    from jsonb_to_recordset(p_registros) as x(
      campo_id uuid,
      fecha date,
      horas numeric,
      volumen_m3 numeric,
      eventos integer
    )
    join public.campos c on c.id = x.campo_id
    where x.fecha >= date '2026-01-01'
      and coalesce(x.volumen_m3, 0) > 0
      and coalesce(x.horas, 0) >= 0
    order by x.campo_id, x.fecha
  )
  insert into public.riego (
    campo_id,
    fecha,
    horas_riego,
    volumen,
    origen,
    wiseconn_volumen_m3,
    wiseconn_horas_calculadas,
    wiseconn_eventos,
    wiseconn_sincronizado_en,
    potrero,
    bloque,
    especie,
    variedad,
    hectareas,
    precipitacion,
    caudal
  )
  select
    e.campo_id,
    e.fecha,
    e.horas,
    e.volumen_m3,
    'wiseconn',
    e.volumen_m3,
    e.horas,
    e.eventos,
    now(),
    e.potrero,
    e.bloque,
    e.especie,
    e.variedad,
    e.hectareas,
    e.precipitacion,
    e.caudal
  from entrada e
  on conflict (campo_id, fecha) do update set
    horas_riego = case
      when coalesce(nullif(riego.origen, ''), 'manual') = 'wiseconn'
        then excluded.horas_riego
      else riego.horas_riego
    end,
    volumen = case
      when coalesce(nullif(riego.origen, ''), 'manual') = 'wiseconn'
        then excluded.volumen
      else riego.volumen
    end,
    origen = case
      when coalesce(nullif(riego.origen, ''), 'manual') = 'wiseconn'
        then 'wiseconn'
      else coalesce(nullif(riego.origen, ''), 'manual')
    end,
    wiseconn_volumen_m3 = excluded.wiseconn_volumen_m3,
    wiseconn_horas_calculadas = excluded.wiseconn_horas_calculadas,
    wiseconn_eventos = excluded.wiseconn_eventos,
    wiseconn_sincronizado_en = excluded.wiseconn_sincronizado_en,
    potrero = excluded.potrero,
    bloque = excluded.bloque,
    especie = excluded.especie,
    variedad = excluded.variedad,
    hectareas = excluded.hectareas,
    precipitacion = excluded.precipitacion,
    caudal = excluded.caudal;

  get diagnostics v_procesados = row_count;

  return jsonb_build_object(
    'procesados', v_procesados,
    'manuales_preservados', v_manuales_preservados,
    'desde', '2026-01-01'
  );
end;
$$;

revoke all on function public.sincronizar_riego_wiseconn(jsonb) from public;
grant execute on function public.sincronizar_riego_wiseconn(jsonb) to authenticated;

commit;

notify pgrst, 'reload schema';

-- Verificacion esperada: 89 zonas sincronizables y 1 zona excluida.
select
  count(*) filter (where sincronizar) as zonas_sincronizables,
  count(*) filter (where not sincronizar) as zonas_excluidas,
  count(*) filter (where sincronizar and campo_id is null) as relaciones_incompletas
from public.wiseconn_zona_campos
where farm_id = 4212;
